Repository GeorgeZCHR/MusicPlayerProject, pull requests merged in 2024-12, with the labels that each got.

#25 initial commit
  musicPlayerProject/src/main/java/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/containers/Song.java
  musicPlayerProject/target/classes/MusicPlayerFrame.class
  musicPlayerProject/target/classes/containers/Song.class
Labels: documentation

#26 Added Database for song/artist/album
  musicPlayerProject/pom.xml
  musicPlayerProject/src/main/java/FirebaseDatabaseManager.java
Labels: enhancement

#36 top 50 Tracks and some artistic fixes
  musicPlayerProject/.idea/dbnavigator.xml
  musicPlayerProject/src/main/java/containers/Track.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/target/classes/containers/Track.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
Labels: enhancement

#41 new gui about create playlist
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/CustomButton.java
  musicPlayerProject/src/main/java/gui/SongSelector.java
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/CustomButton$1.class
  musicPlayerProject/target/classes/gui/CustomButton.class
  musicPlayerProject/target/classes/gui/CustomTextField$1.class
  musicPlayerProject/target/classes/gui/CustomTextField.class
  musicPlayerProject/target/classes/gui/SongSelector.class
Labels: documentation

#42 Playlist Bug was resolved!
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/SongSelector.java
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/SongSelector.class
Labels: bug

#44 the reconstruction is 4/6. 2 contents left
  musicPlayerProject/src/main/java/contents/Content.java
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/contents/OpeningContent.java
  musicPlayerProject/src/main/java/contents/TopArtistsContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/general/Util.java
  musicPlayerProject/target/classes/contents/Content.class
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/contents/OpeningContent.class
  musicPlayerProject/target/classes/contents/TopArtistsContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/general/Util.class
Labels: documentation

#46 reconstruction-of-top-50-tracks
  musicPlayerProject/.idea/dbnavigator.xml
  musicPlayerProject/src/main/java/contents/TopTracksContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/target/classes/contents/TopTracksContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
Labels: documentation

#48 reconstruction-of-bio-content
  musicPlayerProject/src/main/java/contents/BioContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/target/classes/contents/BioContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
Labels: documentation

#50 correct heart button added!
  musicPlayerProject/src/main/java/containers/Song.java
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/containers/Song.class
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: documentation

#52 new guis
  musicPlayerProject/src/main/java/contents/BioContent.java
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/contents/TopArtistsContent.java
  musicPlayerProject/src/main/java/contents/TopTracksContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/general/Util.java
  musicPlayerProject/src/main/java/gui/CustomScrollBarUI.java
  musicPlayerProject/src/main/java/gui/OvalButton.java
  musicPlayerProject/src/main/java/gui/RectButton.java
  musicPlayerProject/src/main/java/gui/RoundButton.java
  musicPlayerProject/src/main/java/gui/WarningFrame.java
  musicPlayerProject/target/classes/contents/BioContent.class
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/contents/TopArtistsContent.class
  musicPlayerProject/target/classes/contents/TopTracksContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/general/Util.class
  musicPlayerProject/target/classes/gui/CustomScrollBarUI$1.class
  musicPlayerProject/target/classes/gui/CustomScrollBarUI$2.class
  musicPlayerProject/target/classes/gui/CustomScrollBarUI.class
  musicPlayerProject/target/classes/gui/OvalButton$1.class
  musicPlayerProject/target/classes/gui/OvalButton.class
  musicPlayerProject/target/classes/gui/RectButton$1.class
  musicPlayerProject/target/classes/gui/RectButton.class
  musicPlayerProject/target/classes/gui/RoundButton$1.class
  musicPlayerProject/target/classes/gui/RoundButton.class
  musicPlayerProject/target/classes/gui/WarningFrame.class
Labels: documentation

#54 bug-fix-of-top-50-albums
  musicPlayerProject/src/main/java/components/GetTopAlbums.java
  musicPlayerProject/src/main/java/contents/TopAlbumsContent.java
  musicPlayerProject/src/main/java/contents/TopArtistsContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/target/classes/components/GetTopAlbums.class
  musicPlayerProject/target/classes/contents/TopAlbumsContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
Labels: bug

#58 button fixes
  musicPlayerProject/.gitignore
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/src/main/java/gui/SongSelector.java
  musicPlayerProject/src/main/java/gui/WarningFrame.java
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/gui/Playlist.class
  musicPlayerProject/target/classes/gui/SongSelector.class
  musicPlayerProject/target/classes/gui/WarningFrame.class
  musicPlayerProject/userCredentials.json
Labels: documentation

#60 User Credentials Bug fixed
  musicPlayerProject/.gitignore
  musicPlayerProject/src/main/java/Main.java
  musicPlayerProject/src/main/java/components/Νέο έγγραφο κειμένου.txt
  musicPlayerProject/target/classes/Main.class
  musicPlayerProject/userCredentials.json
Labels: bug

#68 added remove button for playlist
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/general/Util.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/Main.class
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/general/Util.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: documentation

#69 added functionallity to settings button of main
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/src/main/java/gui/SettingsDropDown.java
  musicPlayerProject/src/main/java/gui/SpecialRoundButton.java
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
  musicPlayerProject/target/classes/gui/SettingsDropDown.class
  musicPlayerProject/target/classes/gui/SpecialRoundButton$1.class
  musicPlayerProject/target/classes/gui/SpecialRoundButton.class
Labels: enhancement

#72 reconstruction of playlist
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: documentation

#73 adding new panel into random playlist
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: enhancement

#77 bug in playlist fixed
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/contents/MusicContent$1.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: bug

#82 MP3 and TopAlbums
  musicPlayerProject/src/main/java/contents/TopAlbumsContent.java
  musicPlayerProject/src/main/java/contents/TurnMp3IntoWAV.java
Labels: enhancement
