Repository GeorgeZCHR/MusicPlayerProject, pull requests merged in 2025-01, with the labels that each got.

#85 top albums and music from api
  musicPlayerProject/img/error_warning.png
  musicPlayerProject/src/main/java/components/MP3ToWAVConverter.java
  musicPlayerProject/src/main/java/components/SongPlayer_Agg.java
  musicPlayerProject/src/main/java/containers/Album.java
  musicPlayerProject/src/main/java/containers/Song.java
  musicPlayerProject/src/main/java/containers/TrackFromAPI.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/contents/SearchResultsContent.java
  musicPlayerProject/src/main/java/contents/TopAlbumsContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/general/Util.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/src/main/java/gui/SongSelector.java
  musicPlayerProject/target/classes/components/ArtistBioSearcher.class
  musicPlayerProject/target/classes/components/FirebaseDatabaseManager$1.class
  musicPlayerProject/target/classes/components/FirebaseDatabaseManager.class
  musicPlayerProject/target/classes/components/FirestoreManager.class
  musicPlayerProject/target/classes/components/GetTopAlbums.class
  musicPlayerProject/target/classes/components/GetTopArtists.class
  musicPlayerProject/target/classes/components/GetTopTracks.class
  musicPlayerProject/target/classes/components/MP3ToWAVConverter$MP3ToPCMInputStream.class
  musicPlayerProject/target/classes/components/MP3ToWAVConverter.class
  musicPlayerProject/target/classes/components/PausablePlayer$1.class
  musicPlayerProject/target/classes/components/PausablePlayer.class
  musicPlayerProject/target/classes/components/SongPlayer_Agg.class
  musicPlayerProject/target/classes/components/User.class
  musicPlayerProject/target/classes/containers/Album.class
  musicPlayerProject/target/classes/containers/Song.class
  musicPlayerProject/target/classes/containers/TrackFromAPI.class
  musicPlayerProject/target/classes/contents/MusicContent$1.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/contents/OpeningContent.class
  musicPlayerProject/target/classes/contents/SearchResultsContent.class
  musicPlayerProject/target/classes/contents/TopAlbumsContent.class
  musicPlayerProject/target/classes/contents/TurnMp3IntoWAV.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame$1.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/general/Util.class
  musicPlayerProject/target/classes/gui/CenterListCellRenderer.class
  musicPlayerProject/target/classes/gui/CustomButton$1.class
  musicPlayerProject/target/classes/gui/CustomButton.class
  musicPlayerProject/target/classes/gui/Playlist.class
  musicPlayerProject/target/classes/gui/SettingsDropDown.class
  musicPlayerProject/target/classes/gui/SongSelector.class
Labels: enhancement

#87 added exit dialog
  musicPlayerProject/src/main/java/gui/ExitDialog.java
Labels: documentation

#89 added profile gui, logout func, some bugs resolved and added loading …
  musicPlayerProject/img/circle-user-blue.png
  musicPlayerProject/img/circle-user-orange.png
  musicPlayerProject/src/main/java/contents/AboutMeContent.java
  musicPlayerProject/src/main/java/contents/LoadingContent.java
  musicPlayerProject/src/main/java/contents/SearchResultsContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/src/main/java/general/Util.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/src/main/java/gui/ProfileDropDown.java
  musicPlayerProject/src/main/java/gui/SettingsDropDown.java
  musicPlayerProject/src/main/java/gui/SongSelector.java
  musicPlayerProject/target/classes/contents/AboutMeContent.class
  musicPlayerProject/target/classes/contents/LoadingContent.class
  musicPlayerProject/target/classes/contents/SearchResultsContent$1.class
  musicPlayerProject/target/classes/contents/SearchResultsContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame$1.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
  musicPlayerProject/target/classes/general/Util.class
  musicPlayerProject/target/classes/gui/ExitDialog.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
  musicPlayerProject/target/classes/gui/ProfileDropDown.class
  musicPlayerProject/target/classes/gui/SettingsDropDown.class
  musicPlayerProject/target/classes/gui/SongSelector.class
Labels: documentation, enhancement

#92 resize functionallity
  musicPlayerProject/src/main/java/contents/AboutMeContent.java
  musicPlayerProject/src/main/java/contents/BioContent.java
  musicPlayerProject/src/main/java/contents/CreatePlaylistContent.java
  musicPlayerProject/src/main/java/contents/LoadingContent.java
  musicPlayerProject/src/main/java/contents/MusicContent.java
  musicPlayerProject/src/main/java/contents/OpeningContent.java
  musicPlayerProject/src/main/java/contents/SearchResultsContent.java
  musicPlayerProject/src/main/java/contents/TopAlbumsContent.java
  musicPlayerProject/src/main/java/contents/TopArtistsContent.java
  musicPlayerProject/src/main/java/contents/TopTracksContent.java
  musicPlayerProject/src/main/java/general/MusicPlayerFrame.java
  musicPlayerProject/target/classes/contents/AboutMeContent.class
  musicPlayerProject/target/classes/contents/BioContent.class
  musicPlayerProject/target/classes/contents/CreatePlaylistContent.class
  musicPlayerProject/target/classes/contents/LoadingContent.class
  musicPlayerProject/target/classes/contents/MusicContent$1.class
  musicPlayerProject/target/classes/contents/MusicContent.class
  musicPlayerProject/target/classes/contents/OpeningContent.class
  musicPlayerProject/target/classes/contents/SearchResultsContent$1.class
  musicPlayerProject/target/classes/contents/SearchResultsContent.class
  musicPlayerProject/target/classes/contents/TopAlbumsContent.class
  musicPlayerProject/target/classes/contents/TopArtistsContent.class
  musicPlayerProject/target/classes/contents/TopTracksContent.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame$1.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame$2.class
  musicPlayerProject/target/classes/general/MusicPlayerFrame.class
Labels: documentation

#95 small fix with playlists from base
  musicPlayerProject/src/main/java/components/FirestoreManager.java
  musicPlayerProject/src/main/java/gui/Playlist.java
  musicPlayerProject/target/classes/components/FirestoreManager.class
  musicPlayerProject/target/classes/gui/Playlist$1.class
  musicPlayerProject/target/classes/gui/Playlist.class
Labels: bug

#97 testing parts
  musicPlayerProject/src/test/java/AlbumGetterSetterTest.java
  musicPlayerProject/src/test/java/ArtistGetterAndSetterTest.java
  musicPlayerProject/src/test/java/ConstructorTest.java
  musicPlayerProject/src/test/java/GetTopTracksTest.java
  musicPlayerProject/src/test/java/TopArtistsAPITest.java
  musicPlayerProject/src/test/java/TrackGetterandSetterTest.java
Labels: enhancement
